//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Using_Api_And_Repository.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Product
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public double price { get; set; }
        public int categoryid { get; set; }
        [JsonIgnore, XmlIgnore]
        public virtual Category Category { get; set; }
    }
}
